sudo: required
services:
  - docker
 
script:
  - docker build -t singh0009/docker-react:latest -f Dockerfile.dev .
  - docker images
  - docker run  -e CI=true singh0009/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-Env"
  bucket_name: "elasticbeanstalk-us-west-2-722416115644"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_Access_Key
  secret_access_key:
    secure: "$AWS_Secret_Key"